### ISSUE TITLE
Use monotonic time

### ISSUE THREAD

**Issue by mikz** [cucumber/cucumber-ruby-core#101]
See https://github.com/ruby-concurrency/concurrent-ruby/issues/256 for reasons why.

I got bitten by this because our app uses timecop to mock with time. Namely it uses scale to make time 1000 times faster.

If you'd be interested, I could make a patch to fix it in https://github.com/cucumber/cucumber-ruby-core/blob/0807c9ca6be06777be75d13a1b769f97ef993399/lib/cucumber/core/test/timer.rb

**Comment by mattwynne** [comment]
Thanks, a patch would be great.

**Comment by mikz** [comment]
@mattwynne great! done cce8a1d. what do you think?

**Comment by mattwynne** [comment]
Looks good, thanks!

**Comment by mattwynne** [comment]
I'm confused where that commit lives! Could you put into a PR for me please and help this scatterbrained over-busy project maintainer? :pray:

**Comment by mikz** [comment]
@mattwynne done! See #103

**Comment by mattwynne** [comment]
Thanks @mikz!
