### ISSUE TITLE
Report summary in commandline will not be displayed when some test case failed

### ISSUE THREAD

**Issue by xuanzhaopeng** [cucumber/cucumber-ruby-core#102]
Hi,

Here is just a improvement we could make, when all test case passed, we will get a summary :

INFO 20160118-124716: report summary of ../target\features-20160118124648.html:

	Finished in 0m23.119s seconds
	13 scenarios (13 passed)
	105 steps (105 passed)

However, when sometimes failed, this message will not be displayed

So maybe we could improve it to show this message all the time.

**Comment by mattwynne** [comment]
Hello.

If this error is about the console output, it needs to be logged in this repo: https://github.com/cucumber/cucumber-ruby

However based on what you've reported, I don't know how to reproduce the problem. I see this output regardless of whether my scenarios have failed or passed. Do you perhaps have something in your test suite that's causing the Ruby process to exit when you have a failure?

**Comment by xuanzhaopeng** [comment]
HI @mattwynne , You r right!!!!! I make a exit when the test case failed!

Thanks a lot
