### ISSUE TITLE
Requiring scenarios

### ISSUE THREAD

**Issue by westlakem** [cucumber/cucumber-ruby-core#104]
I followed the readme on how to get the execution running, but what it doesn't show is how to require the implemented steps.

I tried Dir['D:/devl/ruby/myProject/features/**/*_steps.rb'].each {|f| require f}

but then I got an error of:
NoMethodError: undefined method `register_rb_step_definition' for nil:NilClass

**Comment by tooky** [comment]
Can you give us a little more detail about what you're trying to do? If possible share your code.

Cucumber-Core doesn't have any knowledge of the Cucumber step definition API - which is where `register_rb_step_definition` is called from.

**Comment by westlakem** [comment]
I found a different way to achieve what I was trying to do, using
Cucumber::Runtime

Thanks for your timely response though.
