### ISSUE TITLE
Feature level tags not available during scenario execution

### ISSUE THREAD

**Issue by na-na** [cucumber/cucumber-ruby-core#115]
before_tag(tags) should list the feature level tag for each scenario run

If we have a feature file:

@tag1
Feature: This is a feature
 Scenario: This is a scenario

During execution, the tag list in the before_tags method in formatter does not capture the feature level tags when running the scenario.

Expectation: Feature tags should be available at scenario level as well.

Please let me know if I am correct in my expectation.
Also, let me know if there is a way to know which tag is feature level and which is scenario level.

Thanks!

**Comment by danascheider** [comment]
I'll look into this, but I can tell you right now there won't be a good way to differentiate between feature- and scenario-level tags. I do like the idea of making feature-level tags accessible at the scenario level though.

Thanks for the suggestion @na-na and sorry it's taken so long to get back to you!

**Comment by brasmusson** [comment]
`before_tags` is part of the old formatter API. The recommendation would be to move to the new formatter API as exemplified in [this feature](https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/extending_cucumber/custom_formatter.feature#L18-L34), using [the following events](https://github.com/cucumber/cucumber-ruby/tree/master/lib/cucumber/events)

**Comment by danascheider** [comment]
Thanks for the suggestion @brasmusson!

**Comment by danascheider** [comment]
This issue is resolved using the new events API, @na-na. I just created a PR with tests for it in cucumber/cucumber-ruby#1128.
