### ISSUE TITLE
#outline? method not available on filter stage

### ISSUE THREAD

**Issue by akostadinov** [cucumber/cucumber-ruby-core#119]
Hello, want to use the `Cucumber::Core::Test::Case#outline?` method in the filter stage [1] but it seems that method is available only during execution added by `cucumber`.

Now I'm not really sure whether the `outline?` method should be added in `core` or in `cucumber` but it makes sense to me to be available in `core` directly thus one can always rely on it. Presently my workaround is to use the `Cucumber::Core::Test::Case#keyword` method.

[1] `cucumbler_config.filters << TestCaseManagerFilter.new(...)`

-- core 1.5.0, cucumber 2.4.0

**Comment by akostadinov** [comment]
Actually all `Cucumber::RunningTestCase::ScenarioOutlineExample#methods` seem to me better tobe part of Core:
``` 
  cell_values  outline?  scenario_outline
```

**Comment by brasmusson** [comment]
TestCases (`Cucumber::Core::Test::Case`) are based on the [pickles](https://github.com/cucumber/gherkin#pickles) concept in Gherkin. After compiled from the AST, the Pickles/TestCases should not know whether they came form a Scenario Outline or a regular Scenario, and it should not be necessary to know that to execute the TestCase. In case of formatters, they should rather use the TestCase location to look up from the source things like if the TestCase came from an Scenario Outline or not, than to expect the TestCase object to provide that information. So I disagree, the methods of `Cucumber::RunningTestCase::ScenarioOutlineExample` should not be moved to the core.

**Comment by akostadinov** [comment]
This is not formatters but filters. I'm building a test case manager around the filter feature. So manager checks an external test case management systems whether the scenario should be executed. For the matching the scenario name and parameters (if outline) are used. So I have to act differently depending on scenario type.

I don't know about the pickles concept but at the point of filtering, this information needs to be available so that the feature is useful IMO. The information is actually available but using not so nice API methods.

I'm ok either way - to have the methods available in the pickles or having full-blown test cases passed to the filter.

**Comment by akostadinov** [comment]
bump @brasmusson , would a patch be accepted, given it is about filters, not formatters?

**Comment by brasmusson** [comment]
@akostadinov I recommend not to add an `#outline?` method for the use of filters. I thinks that we should embrace the fact the since v2.0.0 Cucumber-Ruby does not execute features, it executes TestCase:s/[Pickle](https://github.com/cucumber/cucumber/tree/master/gherkin#pickles):s. Currently Cucumber-Ruby does not use the (Pickles) compiler of the Gherkin library, but in my mind I definitely see that it will change in the roadmap of Cucumber-Ruby. From this follows that filtering and execution of TestCase:s/Pickle:s should only rely on the data available in the Pickle Event (see later in the [Pickles](https://github.com/cucumber/cucumber/tree/master/gherkin#pickles) section. I think that also would be very helpful in terms of implementing things like [Parallel Threaded Execution of Scenarios](https://github.com/cucumber/cucumber/issues/89).

**Comment by akostadinov** [comment]
@brasmusson , I couldn't follow exactly what problem you see. Are you against relying on taking decisions based on outline vs non-outline? Or are you just against having an `#outline?` method (in which case the `#keyword` method needs to be used like I wrote in description)?

For filtering purposes, it is IMO useful to know whether something is an outline or normal scenario. Can be used not only for filtering but also for grouping and even for deciding whether something can be executed in parallel or not.

On the other hand, given we have the `#keyword` method already, having a convenience `#outline?` method doesn't sound likely to break any future use cases.

So I will appreciate if you could clarify.

**Comment by brasmusson** [comment]
@akostadinov As I said, as I see the roadmap for Cucumber-Ruby we will start to use the Pickles compiler from the Gherkin library. As you can see later in the [Pickles](https://github.com/cucumber/cucumber/tree/master/gherkin#pickles) section, a Pickle does not contain any information of the keyword (neither for the Pickles/Scenarios, nor for the steps), therefore the `#keyword` method will have to be removed when we start to use the the Pickles compiler from the Gherkin library.

It is possible to determine from a Pickle whether it was created from a Scenario or a Scenario Outline, since the Pickles from the Scenario Outlines have two locations in their locations array. However, I doubt that an `#outline?` method would be particularly useful when no data from the AST is available. I'm worried that adding a `#oultine?` method would encourage users to start to rely on AST data in their filters, so that those filters will not work anymore when we start to use the Pickles compiler from the Gherkin library.

**Comment by akostadinov** [comment]
I see that a lot of important data for filtering will be lost. There would only be file, line and tag metadata carried by the event. It seems like custom filters would be largely useless - we already have tag and file/line filters in core. 

The main use case for me is keeping test case metadata in some external test case management system. For example some tests are only applicable to EBS storage and not NFS for example. Or policy network and not multi-tenant network. Gherkin doesn't have the necessary fields and filtering capabilities to allow anything complicated. Using tags quickly becomes unmanageable. For reporting purposes, there is no built-in mechanism as far as I can tell in Cucumber to reliably map between scenario and some external test case ID (where the external test case ID might be a scenario, an example line, and examples table or a whole scenario outline). 

Presently I achieve this by a custom filter that matches scenarios based on `file`, `scenario name` and `parameters` (the latter when we care about examples). Without the AST metadata, such mapping will also be impossible. For example filter will not know whether we have more examples or we finished with all of them.

I support switching to Pickles as this will simplify the way Cucumber works. Without compromising this simplicity and asking for domain specific additions, I'd ask to have a field in the Pickles with some format specific data. This would be the AST in this situation. It will be only present for this file format.
Users will decide whether to rely on it or not and how to differentiate between different format of feature files.

I think that `uri`, tags and line location are in fact implemented to support existing filters, thus it is IMO a fair call to ask for support of project specific custom filters. I mean, if project relies on format specific conventions to filter test cases, then it makes sense for the project to be allowed to use that. Provided nobody wants to limit possible formats that gherkin can parse from, then project can choose a format that makes sense to them and rely on it's structure to differentiate test cases.
It will also make clear that part of the data is feature format specific, thus users will be responsible to detect that format and handle it accordingly.

Would this be acceptable?

Thanks a lot for your useful replies!

**Comment by enkessler** [comment]
> For reporting purposes, there is no built-in mechanism as far as I can tell in Cucumber to reliably map between scenario and some external test case ID (where the external test case ID might be a scenario, an example line, and examples table or a whole scenario outline).

In my experience, there never will be a way to definitively identify a test that is not made up by the user. Every aspect of a test is alterable (name, location, parameters, etc.). To declare "This is test A and this is test B" in a way that is not subject to change for unrelated reasons pretty much means using tags (e.g. `@test_case_367`, `@JIRA_IMDS12`, etc.).

**Comment by akostadinov** [comment]
@enkessler , this can only partially help. e.g. if you tag a scenario outline example table, then your filter will see the tag. But it will not be able to know when all example lines have been executed so that the status in the external test case management system can be updated to execution completed with success/failure.

On the other hand, if we know such details, then tags or other mechanisms can be used. btw tags allow also to be applied to multiple scenarios and this will make figuring out when all tests are completed even harder.

**Comment by enkessler** [comment]
Extending the tagging idea further, you could track example rows as well by using an extra column.

```
  @test_case_1
  Scenario:
    * a step
    
  @test_case_2
  Scenario Outline:
    * a step with <param 1>
  Examples:
    | param 1 | test_case_id |
    | value 1 | 2-1          |
  Examples: 
    | param 1 | test_case_id |
    | value 1 | 2-2          |
    | value 2 | 2-3          |
```

**Comment by akostadinov** [comment]
@enkessler , what you suggest actually can't work with the Pickles change because Pickle does not give access to the example values. You only get the strings replaced as far as I see but you can't tell that this is an example and can't tell the value of `test_case_id` is `2-2`. This is what I read in @brasmusson's link.

Ability to tag example lines is not the biggest problem though. Would be ugly but one can already create multiple example tables with one example each, then tag the table. If one ever wants to map one example to one test case, it is an option. One has to implement some validation though to make sure all test case tags only match a single scenario or example. 

I'll repeat my last comment and hopefully clarify with an example. Lets imagine I have a scenario outline that as a whole maps to a single external test case:
```
Scenario Outline: Metrics correctly reports used resources
  Given <variant> app is installes
  When I get application metrics
  Then I see 42 <resource> used
Examples: first example table
  | variant      | resource   |
  | cpu_app      | millicores |
  | scalable_app | pods       | 
```

Now I can recognize in some way that I want to update the test case management system with the execution of the scenario outline `Metrics correctly reports used resources`. I get a pickle in my filter with the first example and execute it. But then I have no way to know whether there are more examples. If there are no more examples, then I should go ahead and mark the test case as executed with the correct status. If there are more examples though, I'd have to wait for them to  be executed first, before I set execution result.

This can't be cached till the end of the execution. Execution can take several hours or even a day. Nothing guarantees me that jenkins slave will not die for some reason. Or that some fatal issue would not terminate cucumber before all scenarios are executed thus leaving me with partially executed test cases.

If pickle does not give enough information to reason about outlines and example tables, that would make impossible mapping a whole scenario outline or a whole examples table to a single external test case.

**Comment by enkessler** [comment]
Ah. I see. Pickles are less informative than the current objects used internally.

It sounds like everything is still possible, but it will become more roundabout. Taking your use case specifically, you will receive a pickle and, based on @brasmusson's comment

> It is possible to determine from a Pickle whether it was created from a Scenario or a Scenario Outline, since the Pickles from the Scenario Outlines have two locations in their locations array.

, you can determine if the test is an from an outline and thus may need to wait on additional examples.

In order to determine how many example rows will need to be waited on, it sounds like you will have to use the location information in the pickle to check the source feature yourself and determine how example rows there are for that outline. Again, I'm partial to a tagging solution but if in your case you can rely on the fact that your tests have unique names (e.g. `Metrics correctly reports used resources`) then at the beginning of your run you could parse your test suite and create mapping between test cases and how many rows they have to execute (if any). You formatter could then track how many results it has received for that particular test case and when it has seen all of them then it knows that it can determine the final status of that test case.

**Comment by akostadinov** [comment]
The point is to use parsed information from gherkin instead of implementing things ourselves. I think there is a value to give users the information that is already available. Just provide it in a field that is obvious to be file format specific. In this way, anybody using that information will know other file formats may not work like this.

e.g. if the field is called `format_spefic_location` would indicate one can't rely on this to be universal across all formats

**Comment by enkessler** [comment]
I agree that having more information is better and good abstraction layers have some way to access the underlying layer, if needed. I'm just trying to come up with a solution given the current state of things.

> The point is to use parsed information from gherkin instead of implementing things ourselves.

Sure, and I would never recommend you try to write you own parser. By all means, still rely on  the gherkin gem to do the actual parsing (or [some other suitable tool](https://github.com/enkessler/cuke_modeler)) but, if Cucumber no longer provides access to the parsed information at runtime, you may have to add in that extra parsing step into your larger testing process.

**Comment by brasmusson** [comment]
>  what you suggest actually can't work with the Pickles change because Pickle does not give access to the example values.

With Pickles you also get example values expansion in the name of the scenario outline.
```
Scenario Outline: name (<test_case_id>)
    * a step with <param 1>
  Examples:
    | param 1 | test_case_id |
    | value 1 | 2-1          |
```
will be compiled into a Pickle with the name `name (2-1)`. 

This functionality is available in the compiler in the Gherkin library, but it would actually be really hard to implement the same functionality in the Cucumber-Ruby compiler.

**Comment by akostadinov** [comment]
That's good, we can identify between example lines in this way. Still doesn't let you know how many other examples there are coming.

**Comment by akostadinov** [comment]
bump

**Comment by akostadinov** [comment]
To reiterate, I understand the desire to have a stable public interface. This is awesome. But for some use cases it would also be necessary to get lower level data. It would not be guaranteed to be backward compatible on updates but not completely cut off. And this wouldn't conflict with any new data formats supported.

**Comment by akostadinov** [comment]
Still would like to be able to write filters based on such metadata. If there are future formats that lack such metadata, then it will not be present and filter should cope.
I'm not sure this particular issue for `#outline?` method is so important. But writing custom filters and having all metadata available going forward definitely is.

**Comment by akostadinov** [comment]
@brasmusson , how about a concept like `siblings`? It wouldn't matter what format tests are written in. There would be siblings as well some sort of whatever structure siblings differ from each other. e.g. for Gherkin Outlines it will be as it presently is and if other formats implement some kind of siblings, then it could be something else.

**Comment by akostadinov** [comment]
bump

**Comment by akostadinov** [comment]
bump
