### ISSUE TITLE
Give olleolleolle the commit bit

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby-core#133]
## Summary

[Olle Jonsson](@olleolleolle) has been quietly helping us keep Cucumber-Ruby working on the JVM. I'd like to make it easier for him to contribute.

## Expected Behavior

Exemplify and enforce the [code of conduct](https://github.com/cucumber/cucumber/blob/master/CODE_OF_CONDUCT.md).

Ask if you need anything.

## To do:

- [x] @mattwynne add to @cucumber/cucumber-ruby team on GitHub
- [ ] @mattwynne introduce on https://gitter.com/contributors
- [x] check @olleolleolle has everything he needs

@olleolleolle please close this issue when you're satisfied you have everything you need.

**Comment by olleolleolle** [comment]
Oh, I have everything I need. 👍
