### ISSUE TITLE
Is backports still needed?

### ISSUE THREAD

**Issue by tas50** [cucumber/cucumber-ruby-core#182]
## Summary

The backports gem appears to be used to backport array .to_h functionality for Ruby 2.1, but this gem depends on Ruby 2.3 or later. It would be great to remove the backports dependency if it's not needed since it's 3.9 megs on disk and 1100 files. 

Here's the commit from 4 years ago that added it: https://github.com/cucumber/cucumber-ruby-core/commit/c253221654f7f94fa29b1042c485271d339133e0

## Expected Behavior

Ideally the bare minimum deps would be required

## Current Behavior

backports is used

## Possible Solution

Remove the require and the backports dep

## Steps to Reproduce (for bugs)

N/A

## Context & Motivation

Reducing overall dependency size for customer deployed package.

## Your Environment

* Version used: currently 3.2.1 (I know)
* Operating System and version: macOS 10.15
* Link to your project: https://github.com/chef/chef-workstation

**Comment by luke-hill** [comment]
This looks a nice easy one to fix. Or if you're comfortable, have a go at it yourself.

The cucumber-ruby-core gem is a very thin intermediary layer. So the CI would likely catch it out if something went wrong.

If you're unable to get to it, I can probably do it in the next day or so.

**Comment by tas50** [comment]
Fixed by #185

**Comment by vincent-psarga** [comment]
@luke-hill I think we can safely close it after your last PR right ?

**Comment by luke-hill** [comment]
Should have been closed automatically. As I linked.
