### ISSUE TITLE
Ruby 2.7 can't run rspec

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-ruby-core#187]
## Summary

Ruby 2.7.0 blows up when requiring `protobuf/c` code

## Expected Behavior

`rspec` will run

## Current Behavior

`rspec` crashes with a huge stacktrace

## Your Environment

* Version used: Latest from master
* Operating System and version: Ubuntu 18.04.3 LTS
* Link to your project: this one

**Comment by vincent-psarga** [comment]
Hopefully, this should be fixed with #188 which updates `cucumber-messages` and not rely on `protobuf/c` anymore.
Truth is, it still breaks but differently. I hope to be able to fix it and merge to master so you should be able to integrate that in your PRs :)

**Comment by vincent-psarga** [comment]
Currently the build fails has we have a warning raise due the `private` here: [core/test/result.rb:12](https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/test/result.rb#L12)

To be honest, I don't really understand what it does and how to fix this warning. I see this was written by @brasmusson, could you provide any insight on that by any chance ?

**Comment by vincent-psarga** [comment]
It should be all ok now (#191 fixed the `private` warning and #188 bumped to the latest `gherkin` which uses pure ruby)
