### ISSUE TITLE
Rename Core::Test::Location

### ISSUE THREAD

**Issue by vincent-psarga** [cucumber/cucumber-ruby-core#192]
## Summary

After some discussions with @mattwynne and @aslakhellesoy, we agreed on renaming the `Location` object in `cucumber-ruby-core` so it is clear that it is not the same object than the `Location` object found in `cucumber-messages`.

We're still looking for the proper name, any suggestion is welcome.

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mattwynne** [comment]
The problem is that Location is a great name for this concept :)

We talked about using SourceReference, which is also a concept in the messages protocol but used for something similar.

**Comment by vincent-psarga** [comment]
> The problem is that Location is a great name for this concept :)

Exactly :D I was also thinking about `TestLocation` (which makes it clear it's not the same as a `Location` from messages), but `Test::TestLocation` looks silly ...

**Comment by mattwynne** [comment]
Is it feasible to consider renaming the concept in the messages instead?
