### ISSUE TITLE
Update release process with latest improvements

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/cucumber-ruby-core#229]
While releasing v11.0.0, I noticed that the latest improvements of the release process was missing:

- using the common script to update dependencies
- using `on: workflow_call` to reuse existing workflows and simplify the release workflow rather than relying on an action (will reduce duplication)
- using polyglot_release (requires to use a `VERSION` file rather than `lib/version.rb`)

**Comment by mattwynne** [comment]
done in #236
