### ISSUE TITLE
Ability to modify scenario run status during execution

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby-core#81]
See https://github.com/cucumber/cucumber-ruby-core/issues/73#issuecomment-68928910

User would like to be able to debug / pry a failed step, then resume the scenario. I think this should be possible.

**Comment by danascheider** [comment]
@mattwynne Do you still want this implemented?

**Comment by akostadinov** [comment]
I think originally this request came from me. Still desirable.

**Comment by danascheider** [comment]
Cool, I just wanted to make sure the issue hadn't been resolved some other way before I put the work into it. I'm not entirely sure how this would be implemented but if somebody (@mattwynne or @brasmusson) could point me in the right direction I'd take a stab at it.

**Comment by danascheider** [comment]
What does everybody think about @akostadinov 's suggestion of a `step_failed` hook? We could create a default behavior that could then be overridden if the user wants. Thoughts?

**Comment by danascheider** [comment]
@akostadinov To clarify what you're asking for, you're imagining that whenever any step fails, it drops into pry, and then resumes the scenario when pry exits. In other words, not putting `binding.pry` into the step definition or an after hook.

**Comment by akostadinov** [comment]
@danascheider , yes, if a step fails, user should be able to **optionally** fall into a `pry` shell and **optionally**, after `quit` the scenario should continue.

I'm not sure how this can be done in a pluggable way. The main thing is, from within the shell, to be in the World context or be able to reach it. e.g. in Cucumber v1 I did something like this to get into World context:
```
cd visitor.runtime/@support_code
cd @programming_languages[0].current_world
```

To prevent scenario from failing I could do `@exception = nil`.

Not very pretty but it did the trick. If similar functionality can be implemented for 2.x (in a saner way) that would be really great.

**Comment by danascheider** [comment]
Cool, thanks, that's helpful. I'll start poking at that during my lunch break.

**Comment by akostadinov** [comment]
FYI, this is the exact implementation I had for v1:
```ruby
      Cucumber::Ast::StepInvocation.class_eval do
        ## first make sure we don't lose original accept method
        unless self.instance_methods.include?(:orig_accept)
          alias_method :orig_accept, :accept
        end

        ## wrap original accept method to catch errors in executed step
        def accept(visitor)
          orig_accept(visitor)
          if @exception
            unless @exception.class.name.start_with?("Cucumber::")
              # @exception = nil # to continue with following steps
              # cd visitor.runtime/@support_code
              # cd @programming_languages[0].current_world
              # binding.pry
              # visitor.configuration
              require 'pry'
              binding.pry
            end
          end
        end
```
