### ISSUE TITLE
Test case names for Scenario Outlines contains the non-localized word "row"

### ISSUE THREAD

**Issue by brasmusson** [cucumber/cucumber-ruby-core#83]
The name of a test case for an example scenario from an Scenario Outline is composed as: 
```
"<outline name>, <example table name> (row <number>)"
```
The word "row" is hard-coded in English (in [case.rb](https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/test/case.rb#L128)). "Row" will look a bit odd when using a language other the English in the feature file (especially when using a language not using the Latin alphabet).

Would it be better to use "#" instead of "row", to make the row designation more language neutral?
```
"<outline name>, <example table name> (#<number>)"
```

**Comment by mattwynne** [comment]
Good idea.
