### ISSUE TITLE
Make AST classes more explicitly value objects

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-ruby-core#85]
Criteria:
1. immutable
2. equality comparison works (by location?)

See https://github.com/cucumber/cucumber-ruby-core/commit/2e85fcb5f0f32f52179da67e94c092950d4efed1#commitcomment-10458359

**Comment by mattwynne** [comment]
See also https://github.com/cucumber/cucumber-ruby-core/issues/84

**Comment by brasmusson** [comment]
[this `attr_accessor` in background.rb](https://github.com/cucumber/cucumber-ruby-core/blob/b780c38de23fee2e9e122b35eb21e340cbaac961/lib/cucumber/core/ast/background.rb#L28) should be possible to change to a `attr_reader` (the attributes are set in the constructor). What about [this `attr_accessor` in doc_string.rb](https://github.com/cucumber/cucumber-ruby-core/blob/b780c38de23fee2e9e122b35eb21e340cbaac961/lib/cucumber/core/ast/doc_string.rb#L25) is the `file` attribute ever used? It is not set in the constructor, and I can remove the line from the file without neither the cucumber-ruby-core test nor the cucumber test fails.

**Comment by mattwynne** [comment]
@brasmusson if you can remove it without breaking tests, I'm happy to rip it out.

**Comment by brasmusson** [comment]
All `attr_accessor` declarations are removed from the ast classes (https://github.com/cucumber/cucumber-ruby-core/commit/044cca82b2ef2498517e5c6ef0f9e16e7c3225f7)
