### ISSUE TITLE
How do I use the reporting API in real life?

### ISSUE THREAD

**Issue by JohnSmall** [cucumber/cucumber-ruby-core#91]
Issue: I'm updating a gem that reports on scenario success/fail plus scenario source to an external reporting tool via a REST api. It doesn't work in Cucumber 2.0 so I'm trying to learn how to do it in the Cuke 2.0 world and can't find enough documentation to get started.

I've read through the example of using a reporting class and getting it to work but I'm mystified by two things;-

1) How do I plug in a reporting class into real world Cucumber? I can't believe I'd have to write my own runner and plug the reporting class into that. How do I register my reporting class with real world Cucumber in the features/support/env.rb file ?
2) Having an api to send messages to a report class that responds to certain methods is cool, but Cucumber::Formatter::Html does loads more. Does Cucumber::Formatter::Html behave as a report class, or is it a special case that has a different api?

Is there any documentation or online email conversation I can be pointed to so I can learn how to catch the messages that happen as Cucumber runs and then send information to an external reporting tool?

Thanks

John Small

**Comment by mattwynne** [comment]
Hi John,

I'm really sorry we've not done a better job with this yet. I'm about to disappear offline for a week, but I will endeavour to write something up for you when I'm back, unless @tooky or @brasmusson would care to step in? :)

**Comment by mattwynne** [comment]
What would be great would be a blog post at http://cucumber.io/blog about this.

**Comment by JohnSmall** [comment]
Ah, OK. If you can manage a tiny hint about how to register a new report generator in env.rb so I can get started then I'll take it from there and then blog about my trials and tribulations getting it to work. At the moment I can't find the way in to get started.

My problem with moving my gem up to Cuke 2.x is that the old Scenario object available in the after hook had changed quite a bit. 

The old version of my gem monkey patched Scenario and ScenarioOutline to send results via REST to Testrail from Gurock Software (it's a test reporting package). But I've realised that using an after hook with a monkey patched Scenario is not the way to do it. I'm better off defining a new reporter, plugging that in and getting it to send results via REST to the reporting package.

I'll read the source and see if I can find the way in that doesn't involve creating my own runner.

**Comment by tooky** [comment]
Sorry if I've misunderstood, but the way to use a custom formatter is to include it on the LOAD_PATH and specify it on the command line.

e.g. http://www.relishapp.com/cucumber/cucumber/docs/extending-cucumber/custom-formatter

Does that help?

**Comment by JohnSmall** [comment]
Ah, that's much better than the way I'm trying to do things.

**Comment by brasmusson** [comment]
The most extensive example of the use of the new formatter api (meaning the most data extracted from it), is probably the rewrite of the Json Formatter in cucumber/cucumber#851.

**Comment by JohnSmall** [comment]
Ok, I got that working and it's been running for months now.

**Comment by mattwynne** [comment]
Glad to hear it.
On Tue, 16 Feb 2016 at 13:19, John Small <notifications@github.com> wrote:

> Closed #91 <https://github.com/cucumber/cucumber-ruby-core/issues/91>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cucumber/cucumber-ruby-core/issues/91#event-552006574>
> .
>

-- 



The Cucumber logo is the intellectual property of Cucumber Ltd, a limited 
company registered in Scotland, number 456793.

UK Headquarters: Cucumber Ltd, Drumsyniebeg, Lochgoilhead, Cairndow, 
Argyll, PA24 8AN UK.

CONFIDENTIALITY NOTICE: The information in this e-mail is confidential and 
privileged; it is intended for use solely by the individual or entity named 
as the recipient hereof. Disclosure, copying, distribution, or use of the 
contents of this e-mail by persons other than the intended recipient is 
strictly prohibited and may violate applicable laws. If you have received 
this e-mail in error, please delete the original message and notify us by 
email immediately. Thank you. Cucumber Ltd.
